spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  rabbitmq:
    host: localhost
    port: 5672
    username: qianyanglong
    password: wansui
    virtual-host: qianyanglongdexuniji
eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
hystrix.command.default:
  execution.isolation.thread.timeoutInMilliseconds: 10000   